# Please run rake spa:fetch to update this file
---
production:
  spa.js: https://lml-seo.web.app/rails_spa/lml.js
  spa.css: https://lml-seo.web.app/rails_spa/assets/styles-BpJa-Giv.css
development:
  spa.js: https://lml-seo.web.app/rails_spa/lml.js
  spa.css: https://lml-seo.web.app/rails_spa/assets/styles-BpJa-Giv.css
