# Please run rake spa:fetch to update this file
---
production:
  spa.js: https://assets.livemusiclocator.com.au/rails_spa/assets/index-CXov-FC6.js
  spa.css: https://assets.livemusiclocator.com.au/rails_spa/assets/styles-DcoX_9bF.css
development:
  spa.js: https://assets.livemusiclocator.com.au/rails_spa/assets/index-CXov-FC6.js
  spa.css: https://assets.livemusiclocator.com.au/rails_spa/assets/styles-DcoX_9bF.css
test:
  spa.js: https://assets.livemusiclocator.com.au/rails_spa/assets/index-CXov-FC6.js
  spa.css: https://assets.livemusiclocator.com.au/rails_spa/assets/styles-DcoX_9bF.css
