# Please run rake spa:fetch to update this file
---
production:
  spa.js: https://assets.livemusiclocator.com.au/lml_gig_explorer_beta/lml_gig_explorer.js
  spa.css: https://assets.livemusiclocator.com.au/lml_gig_explorer_beta/lml_gig_explorer.css
test:
  spa.js: https://assets.livemusiclocator.com.au/lml_gig_explorer_beta/lml_gig_explorer.js
  spa.css: https://assets.livemusiclocator.com.au/lml_gig_explorer_beta/lml_gig_explorer.css
development:
  spa.js: https://assets.livemusiclocator.com.au/lml_gig_explorer_dev/lml_gig_explorer.js
  spa.css: https://assets.livemusiclocator.com.au/lml_gig_explorer_dev/lml_gig_explorer.css
